// End-to-end tests run ONLY against the disposable Supabase stack created by CI.
const assert = require("node:assert/strict");
const fs = require("node:fs");
const { execFileSync } = require("node:child_process");
const { createClient } = require("@supabase/supabase-js");
const { chromium } = require("playwright");
const url=process.env.API_URL,anon=process.env.ANON_KEY,service=process.env.SERVICE_ROLE_KEY;
assert.match(url,/^http:\/\/(127\.0\.0\.1|localhost):54321/,"Refuse to test a hosted database");
fs.mkdirSync("test-results",{recursive:true});
const evidence=[];
const record=(name)=>{evidence.push({name,result:"passed"});console.log("PASS:",name)};
const sql=(q)=>execFileSync("psql",[process.env.DB_URL,"-v","ON_ERROR_STOP=1","-At","-c",q],{encoding:"utf8"}).trim();
const root=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
const password="Local-ci-only-42!";
const users={};
async function make(role,name){
 const email=name+"@laudos.example.test";
 const {data,error}=await root.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:name}});
 assert.ifError(error);
 sql("update public.pilot_profiles set role='"+role+"',status='Ativo',active=true where id='"+data.user.id+"'");
 const client=createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false}});
 const login=await client.auth.signInWithPassword({email,password});assert.ifError(login.error);
 users[name]={client,id:data.user.id,email,role};return client;
}
async function rpc(client,name,args){const r=await client.rpc(name,args);assert.ifError(r.error);return r.data}
async function denied(client,name,args,pattern){const r=await client.rpc(name,args);assert.ok(r.error,"Expected RPC rejection: "+name);if(pattern)assert.match(r.error.message,pattern);return r.error}
const specs=[{name:"pH",unit:"pH",min:6,max:8,required:true},{name:"Aspecto",unit:"",qual:["Límpido"],required:true}];
const cycleArgs=(tank,product,values=["7","Límpido"])=>({p_tank_id:tank,p_product_id:product,p_manufactured_at:new Date().toISOString(),p_lots:"L-CI",p_reference:values,p_analyst:"Analista CI"});
const loadingArgs=(cycle,destination,plate="ABC1234",values=["7","Límpido"],source="own")=>({p_cycle_id:cycle,p_plate:plate,p_trailer:"Única",p_carrier:"Transportadora CI",p_destination:destination,p_analyst:"Analista CI",p_loaded_at:new Date().toISOString(),p_values:values,p_source:source,p_observation:"Verificação isolada"});
let browser,lastPage;
(async()=>{
 const admin=await make("Administrador","admin"),sup=await make("Supervisor","supervisor"),tech=await make("Operador Técnico","tecnico"),operator=await make("Operador A","operador"),consulta=await make("Consulta","consulta");
 await make("Administrador","admin2");
 record("Auth: login real nos cinco perfis");
 for(const [name,u] of Object.entries(users)){
  const perms=await rpc(u.client,"pilot_permissions",{});
  assert.equal(perms.includes("products.manage"),u.role==="Administrador");
  assert.equal(perms.includes("users.manage"),["Administrador","Supervisor"].includes(u.role));
  assert.equal(perms.includes("cancellations.decide"),["Administrador","Supervisor","Operador Técnico"].includes(u.role));
 }
 record("Matriz central de permissões nos cinco perfis");
 const legacy=await consulta.from("pilot_loadings").select("*").eq("id",-100).single();assert.ifError(legacy.error);assert.equal(legacy.data.destination,"Uberaba");assert.equal(legacy.data.destination_id,null);
 assert.equal((await rpc(consulta,"pilot_certificate_details",{p_id:-100})).loading_id,-100);
 record("Migração: destino genérico Uberaba preservado e Consulta global");
 const oldRequests=await operator.from("pilot_authorization_requests").select("*").in("loading_id",[-101,-102]);assert.ifError(oldRequests.error);assert.equal(oldRequests.data.length,2);assert.ok(oldRequests.data.every(r=>r.legacy&&r.requester_name&&r.requested_at));
 await rpc(tech,"pilot_decide",{p_id:-101,p_kind:"reuse",p_approve:true,p_reason:"Pendência antiga conferida"});await rpc(operator,"pilot_issue",{p_id:-101});
 record("Migração: autorizações antigas concluídas/pendentes preservadas e fluxo legado continua funcionando");
 const destinations=await admin.from("pilot_destinations").select("*").order("display_order");assert.ifError(destinations.error);assert.equal(destinations.data.length,11);assert.equal(new Set(destinations.data.map(d=>d.id)).size,11);
 const product=await rpc(admin,"pilot_save_product",{p_code:"CI-001",p_name:"Resina CI",p_family:"Resina",p_specs:specs});
 await denied(admin,"pilot_save_product",{p_code:" ci-001 ",p_name:"Duplicado",p_family:"Resina",p_specs:specs},/código/);
 await denied(operator,"pilot_save_product",{p_code:"CI-002",p_name:"Não permitido",p_family:"Resina",p_specs:specs},/Acesso/);
 record("Produto: criação, unicidade normalizada e bloqueio no backend");
 const t1=await rpc(admin,"pilot_save_tank",{p_code:"T-CI-1",p_family:"Resina"}),t2=await rpc(admin,"pilot_save_tank",{p_code:"T-CI-2",p_family:"Resina"}),t3=await rpc(admin,"pilot_save_tank",{p_code:"T-CI-3",p_family:"Resina"});
 await denied(operator,"pilot_create_cycle",cycleArgs(t1,product,["","Límpido"]),/obrigatória/);
 await denied(operator,"pilot_create_cycle",cycleArgs(t1,product,["NaN","Límpido"]),/numérico inválido/);
 const c1=await rpc(operator,"pilot_create_cycle",cycleArgs(t1,product));
 const c2=await rpc(operator,"pilot_create_cycle",cycleArgs(t2,product));
 assert.equal(sql("select product_snapshot->>'name' from public.pilot_cycles where id="+c1),"Resina CI");
 record("Ciclo de tanque: validação obrigatória, criação e snapshot");
 const cancellation=await rpc(operator,"pilot_request_cancellation",{p_kind:"cancel_cycle",p_id:c2,p_reason:"Tanque incorreto"});
 await denied(operator,"pilot_decide_cancellation",{p_request_id:cancellation,p_approve:true,p_reason:"Confirmado"},/Acesso/);
 await rpc(tech,"pilot_decide_cancellation",{p_request_id:cancellation,p_approve:true,p_reason:"Confirmado erro operacional"});
 assert.equal(sql("select status||':'||active::text from public.pilot_cycles where id="+c2),"Cancelado:false");
 const cancelledCycle=await sup.from("pilot_cycles").select("*").eq("id",c2).single();assert.ifError(cancelledCycle.error);
 const c3=await rpc(operator,"pilot_create_cycle",cycleArgs(t3,product));await rpc(tech,"pilot_close_cycle",{p_id:c3});
 assert.equal(sql("select status from public.pilot_cycles where id="+c3),"Encerrado");
 assert.ifError((await sup.from("pilot_cycles").select("*").eq("id",c3).single()).error);
 record("Ciclo: cancelamento autorizado, tentativa sem permissão, histórico e encerramento");
 const ids=[];
 for(const [i,d] of destinations.data.entries()){
  const id=await rpc(operator,"pilot_create_loading",loadingArgs(c1,d.id,"UNI"+String(i).padStart(4,"0")));ids.push(id);
  const l=await operator.from("pilot_loadings").select("*").eq("id",id).single();assert.ifError(l.error);assert.equal(l.data.destination_id,d.id);assert.equal(l.data.destination,d.name);
 }
 await denied(operator,"pilot_create_loading",loadingArgs(c1,"Uberaba","BAD1234"),/unidade/);
 record("Todas as onze unidades: seleção, identificação estável e texto armazenado");
 await denied(tech,"pilot_close_cycle",{p_id:c1},/pendentes/);
 await denied(operator,"pilot_request_cancellation",{p_kind:"cancel_cycle",p_id:c1,p_reason:"Erro operacional"},/vinculados/);
 record("Dependências: encerramento com pendências e cancelamento com vínculos bloqueados");
 const normal=ids[0];const number=await rpc(operator,"pilot_issue",{p_id:normal});assert.ok(number);
 await denied(operator,"pilot_save_loading",{p_id:normal,...Object.fromEntries(Object.entries(loadingArgs(c1,destinations.data[0].id)).filter(([k])=>k!=="p_cycle_id"))},/editado/);
 const direct=await operator.from("pilot_loadings").update({plate:"HACK123"}).eq("id",normal);assert.ok(direct.error);
 record("Laudo: emissão normal e proibição de edição por RPC/chamada direta");
 const reused=await rpc(operator,"pilot_create_loading",loadingArgs(c1,destinations.data[1].id,"REF1234",["7","Límpido"],"ref"));
 await rpc(operator,"pilot_request_approval",{p_id:reused});
 let req=await operator.from("pilot_authorization_requests").select("*").eq("loading_id",reused);assert.ifError(req.error);assert.equal(req.data[0].requester_name,"operador");assert.ok(req.data[0].requested_at);
 await denied(operator,"pilot_decide",{p_id:reused,p_kind:"reuse",p_approve:true,p_reason:"Aprovado"},/Acesso/);
 await rpc(tech,"pilot_decide",{p_id:reused,p_kind:"reuse",p_approve:true,p_reason:"Referências verificadas"});
 await rpc(operator,"pilot_issue",{p_id:reused});
 const trace=await rpc(consulta,"pilot_certificate_details",{p_id:reused});assert.equal(trace.approvals[0].name,"tecnico");
 record("Uso de análises do tanque: solicitação, Operador Técnico, emissão e rastreabilidade");
 const abnormal=await rpc(operator,"pilot_create_loading",loadingArgs(c1,destinations.data[2].id,"EXC1234",["9","Límpido"]));
 await rpc(operator,"pilot_request_approval",{p_id:abnormal});
 await denied(tech,"pilot_decide",{p_id:abnormal,p_kind:"exception",p_approve:true,p_reason:"Não permitido"},/Acesso/);
 await rpc(sup,"pilot_decide",{p_id:abnormal,p_kind:"exception",p_approve:false,p_reason:"Refazer análise"});
 const saveArgs=loadingArgs(c1,destinations.data[2].id,"EXC1234",["9","Límpido"]);delete saveArgs.p_cycle_id;
 await rpc(operator,"pilot_save_loading",{p_id:abnormal,...saveArgs});
 await rpc(operator,"pilot_request_approval",{p_id:abnormal});
 await rpc(sup,"pilot_decide",{p_id:abnormal,p_kind:"exception",p_approve:true,p_reason:"Exceção justificada"});
 await rpc(operator,"pilot_issue",{p_id:abnormal});
 req=await operator.from("pilot_authorization_requests").select("*").eq("loading_id",abnormal);assert.ifError(req.error);assert.equal(req.data.length,2);assert.deepEqual(new Set(req.data.map(r=>r.decision)),new Set(["rejected","approved"]));
 assert.ok(req.data.every(r=>r.requester_name&&r.actor_name&&r.requested_at&&r.decided_at));
 assert.ok(req.data.some(r=>r.reason.includes("pH = 9")));
 record("Exceção: autorização restrita, rejeição, correção, aprovação e histórico permanente");
 const cancelRejected=await rpc(operator,"pilot_request_cancellation",{p_kind:"cancel_certificate",p_id:normal,p_reason:"Placa informada incorretamente"});
 await rpc(tech,"pilot_decide_cancellation",{p_request_id:cancelRejected,p_approve:false,p_reason:"Conferir informação"});
 assert.equal(sql("select state from public.pilot_loadings where id="+normal),"Emitido");
 const cancelApproved=await rpc(operator,"pilot_request_cancellation",{p_kind:"cancel_certificate",p_id:normal,p_reason:"Erro confirmado na placa"});
 await rpc(tech,"pilot_decide_cancellation",{p_request_id:cancelApproved,p_approve:true,p_reason:"Correção necessária"});
 assert.equal(sql("select state from public.pilot_loadings where id="+normal),"Cancelado");
 assert.equal(sql("select certificate_number from public.pilot_loadings where id="+normal),number);
 assert.ifError((await consulta.from("pilot_loadings").select("*").eq("id",normal).single()).error);
 assert.equal((await rpc(consulta,"pilot_certificate_details",{p_id:normal})).loading_id,normal);
 await denied(operator,"pilot_issue",{p_id:normal},/indisponível/);
 const corrected=await rpc(operator,"pilot_create_loading",loadingArgs(c1,destinations.data[0].id,"COR1234"));
 await rpc(operator,"pilot_issue",{p_id:corrected});
 record("Cancelamento de laudo: rejeição/aprovação, original consultável, nova emissão correta");
 await rpc(admin,"pilot_save_product",{p_id:product,p_code:"CI-001",p_name:"Resina CI versão 2",p_family:"Resina",p_specs:[{...specs[0],max:10},specs[1]]});
 assert.equal(sql("select count(*) from public.pilot_product_versions where product_id="+product),"2");
 assert.equal(sql("select product_snapshot->>'name' from public.pilot_cycles where id="+c1),"Resina CI");
 assert.equal(sql("select specifications->0->>'max' from public.pilot_cycles where id="+c1),"8");
 assert.equal(sql("select author_name from public.pilot_product_versions where product_id="+product+" and version=2"),"admin");
 await rpc(admin,"pilot_set_product_active",{p_id:product,p_active:false});
 await denied(operator,"pilot_create_cycle",cycleArgs(t2,product),/incompatíveis/);
 await denied(operator,"pilot_create_loading",loadingArgs(c1,destinations.data[0].id,"INA1234"),/inativo/);
 assert.equal((await rpc(consulta,"pilot_certificate_details",{p_id:reused})).loading_id,reused);
 await rpc(admin,"pilot_set_product_active",{p_id:product,p_active:true});
 record("Produtos: versões completas, inativação, bloqueio de novos usos e histórico imutável");
 const allUsers=await rpc(admin,"pilot_list_users",{}),below=await rpc(sup,"pilot_list_users",{});
 assert.ok(allUsers.some(u=>u.role==="Administrador"));assert.ok(below.every(u=>["Operador Técnico","Operador A","Consulta"].includes(u.role)));
 await rpc(sup,"pilot_update_user",{p_id:users.operador.id,p_name:"Operador atualizado",p_role:"Operador A",p_status:"Ativo",p_reason:"Nome corrigido"});
 await denied(sup,"pilot_update_user",{p_id:users.admin.id,p_name:"Alteração",p_role:"Consulta",p_status:"Ativo",p_reason:"Tentativa"},/abaixo/);
 await denied(sup,"pilot_update_user",{p_id:users.operador.id,p_name:"Alteração",p_role:"Administrador",p_status:"Ativo",p_reason:"Tentativa"},/abaixo/);
 await denied(operator,"pilot_update_user",{p_id:users.consulta.id,p_name:"Alteração",p_role:"Operador A",p_status:"Ativo",p_reason:"Tentativa"},/Acesso/);
 const pending=await root.auth.admin.createUser({email:"pending@laudos.example.test",password,email_confirm:true,user_metadata:{full_name:"Consulta aprovada"}});assert.ifError(pending.error);
 await rpc(sup,"pilot_decide_profile",{p_user_id:pending.data.user.id,p_approve:true,p_role:"Consulta",p_destination:null,p_reason:"Acesso de consulta"});
 assert.equal(sql("select status from public.pilot_profiles where id='"+pending.data.user.id+"'"),"Ativo");
 assert.equal((await rpc(operator,"pilot_list_users",{})).length,0);
 const selfOnly=await sup.from("pilot_profiles").select("*");assert.ifError(selfOnly.error);assert.equal(selfOnly.data.length,1);
 record("Usuários: lista hierárquica, edição, aprovação Consulta global e bloqueio de acesso direto/escalada");
 const audit=await admin.from("pilot_audit").select("*").in("entity",["pilot_products","pilot_authorization_requests"]);
 assert.ifError(audit.error);assert.ok(audit.data.some(a=>a.details.before&&a.details.after));
 const consultation=await consulta.from("pilot_loadings").select("*");assert.ifError(consultation.error);
 assert.ok(consultation.data.every(l=>l.certificate_number&&["Emitido","Cancelado"].includes(l.state)));
 assert.ok(new Set(consultation.data.map(l=>l.destination)).size>=3);
 await denied(consulta,"pilot_request_cancellation",{p_kind:"cancel_certificate",p_id:corrected,p_reason:"Tentativa"},/Acesso/);
 record("RLS: Consulta global sem rascunhos, ações bloqueadas e auditoria antes/depois");
 // Real browser + actual Supabase Auth/RPC/database; no network mocks.
 await rpc(admin,"pilot_save_tank",{p_code:"WEB-TANK",p_family:"Resina"});
 browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();lastPage=page;page.setDefaultTimeout(15000);
 const consoleErrors=[];page.on("response",r=>{if(r.status()>=400){const u=new URL(r.url());console.log("HTTP_FAILURE",r.status(),r.request().method(),u.pathname)}});page.on("pageerror",e=>consoleErrors.push(e.message));page.on("console",m=>{if(m.type()==="error")consoleErrors.push(m.text()+" @ "+m.location().url)});
 async function nav(name){await page.locator(".sidebar nav").getByRole("button",{name,exact:true}).click();}
 async function login(name){await page.goto("http://127.0.0.1:5173");await page.getByLabel("E-mail",{exact:true}).fill(users[name].email);await page.getByLabel("Senha",{exact:true}).fill(password);await page.getByRole("button",{name:"Entrar",exact:true}).click();await page.locator(".sidebar").waitFor();}
 await login("operador");
 await nav("Início");
 const lastStep=page.locator(".flow-card").filter({hasText:"Emita e consulte o laudo"});
 assert.equal(await lastStep.getByRole("button").count(),1);
 await lastStep.getByRole("button",{name:"Ver laudos",exact:true}).click();
 await page.getByRole("heading",{name:"Laudos emitidos",exact:true}).waitFor();
 await nav("Início");
 await page.locator(".home-heading").getByRole("button",{name:"Ajuda",exact:true}).click();
 const manual=page.getByRole("dialog",{name:"Manual operacional",exact:true});
 await manual.waitFor();
 await manual.getByRole("button",{name:"9. Corrigir um laudo já emitido",exact:true}).click();
 assert.equal(await page.evaluate(()=>document.activeElement.id),"manual-cancelamento-laudo");
 const manualSearch=manual.getByRole("searchbox",{name:"Buscar no manual",exact:true});
 await manualSearch.fill("autorizacao");await manual.getByRole("heading",{name:"7. Solicitar e decidir autorizações",exact:true}).waitFor();
 await manualSearch.fill("zzzzzzzz");await manual.getByText("Nenhum tópico encontrado. Tente outra palavra ou limpe a busca.",{exact:true}).waitFor();
 await manualSearch.fill("cancelamento");
 const [download]=await Promise.all([page.waitForEvent("download"),manual.getByRole("link",{name:"Baixar manual",exact:true}).click()]);
 assert.equal(download.suggestedFilename(),"Laudos-Agudos-Manual-Operacional.md");
 await download.saveAs("test-results/manual-download.md");
 const manualText=fs.readFileSync("test-results/manual-download.md","utf8");
 assert.match(manualText,/15\. Preservar a rastreabilidade/);assert.match(manualText,/Agudos - MDF1/);assert.match(manualText,/Taquari - Revestidos/);
 await page.emulateMedia({media:"print"});
 assert.equal(await manual.locator(".manual-section:visible").count(),15);
 assert.equal(await page.locator(".shell").isVisible(),false);
 await page.pdf({path:"test-results/manual-operacional.pdf",format:"A4",printBackground:true});
 const manualPages=(fs.readFileSync("test-results/manual-operacional.pdf").toString("latin1").match(/\/Type\s*\/Page\b/g)||[]).length;
 assert.ok(manualPages>=4,"The complete manual must print across multiple pages");console.log("MANUAL_PDF_PAGES",manualPages);
 await page.emulateMedia({media:"screen"});await manualSearch.fill("");
 for(const width of [1280,1920]){
  await page.setViewportSize({width,height:1000});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:"test-results/manual-"+width+".png",fullPage:true});
  if(width===1280)console.log("VISUAL_MANUAL:"+(await page.screenshot({type:"jpeg",quality:60})).toString("base64"));
 }
 await page.setViewportSize({width:1440,height:1000});
 await manual.getByRole("button",{name:"Fechar manual",exact:true}).click();await manual.waitFor({state:"hidden"});
 record("Navegador: card final, ajuda inicial, sumário, busca sem acento, download completo e impressão");
 await nav("Ciclos de tanques");await page.getByRole("button",{name:"Novo Ciclo de tanque",exact:true}).click();
 await page.locator('[data-field="tank_id"] select').selectOption({label:"WEB-TANK · Resina"});
 await page.locator('[data-field="product_id"] select').selectOption({label:"Resina CI versão 2 · v4"});
 await page.getByRole("combobox",{name:"Lotes",exact:true}).fill("WEB-LOTE");
 await page.getByRole("button",{name:"Criar Ciclo de tanque",exact:true}).click();
 await page.locator(".invalid-field").first().waitFor();
 assert.ok(await page.getByText("Especificação:",{exact:false}).count()>=2);
 await page.getByRole("combobox",{name:"pH",exact:true}).fill("7");
 await page.getByRole("combobox",{name:"Aspecto",exact:true}).fill("Límpido");
 await page.getByRole("button",{name:"Criar Ciclo de tanque",exact:true}).click();
 await page.locator(".card-grid").getByText("WEB-LOTE",{exact:false}).waitFor();
 await page.screenshot({path:"test-results/tank-cycles-1440.png",fullPage:true});console.log("VISUAL_CYCLES:"+ (await page.screenshot({type:"jpeg",quality:65})).toString("base64"));
 record("Navegador: login/navegação, Ciclo de tanque, limites compartilhados e erro obrigatório visível");
 const webCard=page.locator(".card-grid .card").filter({hasText:"WEB-LOTE"});
 const consultButton=webCard.getByRole("button",{name:"Consultar",exact:true});
 const cancellationButton=webCard.getByRole("button",{name:"Solicitar cancelamento",exact:true});
 for(const control of [consultButton,cancellationButton]){
  const bounds=await control.boundingBox();assert.ok(bounds.width<=36&&bounds.height<=36);
  assert.equal(await control.innerText(),"");
 }
 await consultButton.click();await page.getByRole("dialog",{name:"Consultar Ciclo de tanque",exact:true}).waitFor();
 await page.getByRole("button",{name:"Fechar",exact:true}).click();
 await cancellationButton.click();await page.getByRole("dialog",{name:"Solicitar cancelamento",exact:true}).waitFor();
 await page.getByRole("button",{name:"Voltar",exact:true}).click();
 await webCard.getByRole("button",{name:"Novo carregamento",exact:true}).click();
 await page.getByRole("button",{name:"Salvar rascunho",exact:true}).click();
 await page.locator(".invalid-field").first().waitFor();
 assert.equal(await page.locator('[data-field="plate"] [aria-invalid="true"]').count(),1);
 await page.getByRole("combobox",{name:"Placa",exact:true}).fill("WEB1234");
 await page.locator(".sidebar nav").getByRole("button",{name:"Ajuda",exact:true}).click();await manual.waitFor();
 await page.keyboard.press("Escape");await manual.waitFor({state:"hidden"});
 assert.equal(await page.getByRole("combobox",{name:"Placa",exact:true}).inputValue(),"WEB1234");
 await page.getByRole("combobox",{name:"Transportadora",exact:true}).fill("Transportadora WEB");
 await page.getByLabel("Unidade / destino *",{exact:true}).selectOption("taquari-revestidos");
 await page.getByRole("combobox",{name:"pH",exact:true}).fill("7");
 await page.getByRole("combobox",{name:"Aspecto",exact:true}).fill("Límpido");
 await page.getByRole("button",{name:"Salvar rascunho",exact:true}).click();
 await page.getByText("Rascunho salvo.",{exact:true}).waitFor();
 await page.getByRole("button",{name:"Emitir laudo",exact:true}).click();
 await page.locator(".certificate").waitFor();
 const issuer=page.locator(".cert-responsibles dl > div").filter({has:page.locator("dt",{hasText:"Emissão do laudo"})}).locator("dd");
 await issuer.getByText("operador",{exact:true}).waitFor();assert.equal(await issuer.innerText(),"operador");
 const certFields=await page.locator(".cert-grid > span").allTextContents();
 assert.ok(!certFields.some(field=>field.startsWith("Especificação")));
 assert.match(certFields.find(field=>field.startsWith("Carregamento")),/^Carregamento\d{2}\/\d{2}\/\d{4}$/);
 assert.match(certFields.find(field=>field.startsWith("Emissão")),/\d{2}:\d{2}/);
 await page.screenshot({path:"test-results/certificate-1440.png",fullPage:true});console.log("VISUAL_CERTIFICATE:"+ (await page.screenshot({type:"jpeg",quality:65})).toString("base64"));
 record("Navegador: carregamento, erro localizado, unidade estruturada, rascunho e emissão real");

 await nav("Ciclos de tanques");
 const endedRow=page.locator("tbody tr").filter({hasText:"T-CI-2"});
 await endedRow.getByRole("button",{name:"Consultar",exact:true}).click();
 await page.getByRole("dialog",{name:"Consultar Ciclo de tanque",exact:true}).waitFor();
 assert.equal(await page.locator(".wide-modal").getByRole("button",{name:"Consultar",exact:true}).count(),0);
 assert.ok(await page.locator(".wide-modal").getByText("Tanque incorreto",{exact:false}).count());
 await page.getByRole("button",{name:"Fechar",exact:true}).click();
 const closedRow=page.locator("tbody tr").filter({hasText:"T-CI-3"});
 await closedRow.getByRole("button",{name:"Consultar",exact:true}).click();
 const closedDialog=page.getByRole("dialog",{name:"Consultar Ciclo de tanque",exact:true});await closedDialog.waitFor();
 await closedDialog.getByRole("heading",{name:/Encerrado/}).waitFor();
 assert.equal(await closedDialog.getByRole("button").count(),1);
 await closedDialog.getByRole("button",{name:"Fechar",exact:true}).click();
 record("Navegador: laudo sem perfil do emissor/versão da especificação, carregamento só com data, emissão com horário e histórico encerrado sem botão redundante");
 await page.locator(".card-grid .card").filter({hasText:"WEB-LOTE"}).getByRole("button",{name:"Novo carregamento",exact:true}).click();
 await page.getByRole("combobox",{name:"Placa",exact:true}).fill("WEB5678");
 await page.getByRole("combobox",{name:"Transportadora",exact:true}).fill("Transportadora WEB");
 await page.getByLabel("Unidade / destino *",{exact:true}).selectOption("uberaba-mdp");
 await page.getByLabel("Origem dos resultados",{exact:true}).selectOption("ref");
 await page.getByRole("button",{name:"Solicitar autorização",exact:true}).click();
 await page.getByText("Solicitação enviada. O responsável já pode avaliar.",{exact:true}).waitFor();
 await page.getByRole("button",{name:"Sair",exact:true}).click();await page.getByLabel("E-mail",{exact:true}).waitFor();await login("tecnico");
 await nav("Autorizações");await page.getByRole("button",{name:"Autorizar referência",exact:true}).click();
 await page.getByLabel("Justificativa obrigatória",{exact:true}).fill("Referências conferidas no navegador");
 await page.getByRole("button",{name:"Registrar decisão",exact:true}).click();
 await page.getByText("Decisão registrada.",{exact:true}).waitFor();
 await page.getByRole("button",{name:"Sair",exact:true}).click();await page.getByLabel("E-mail",{exact:true}).waitFor();await login("operador");
 await nav("Carregamentos");
 const approvedRow=page.locator("tbody tr").filter({hasText:"WEB5678"});
 await approvedRow.getByText("Autorizado para emissão",{exact:true}).waitFor();await approvedRow.click();
 await page.getByRole("button",{name:"Emitir laudo",exact:true}).click();await page.locator(".certificate").waitFor();
 await page.getByRole("button",{name:"Solicitar cancelamento",exact:true}).click();
 await page.getByLabel("Motivo obrigatório",{exact:true}).fill("Erro operacional conferido na interface");
 await page.getByRole("button",{name:"Enviar solicitação",exact:true}).click();await page.getByText("Cancelamento solicitado.",{exact:true}).waitFor();
 await page.getByRole("button",{name:"Sair",exact:true}).click();await page.getByLabel("E-mail",{exact:true}).waitFor();await login("tecnico");
 await nav("Autorizações");await page.getByRole("button",{name:"Autorizar",exact:true}).click();
 await page.getByLabel("Justificativa obrigatória",{exact:true}).fill("Cancelamento confirmado no navegador");
 await page.getByRole("button",{name:"Registrar decisão",exact:true}).click();await page.getByText("Decisão registrada.",{exact:true}).waitFor();
 assert.equal(sql("select state from public.pilot_loadings where plate='WEB5678'"),"Cancelado");
 record("Navegador: consulta de Ciclo cancelado, solicitação de referência, aprovação, estado sincronizado, emissão e cancelamento autorizado");

 await page.getByRole("button",{name:"Sair",exact:true}).click();await page.getByLabel("E-mail",{exact:true}).waitFor();await login("admin");
 await nav("Ciclos de tanques");
 for(const width of [1280,1920]){
  await page.setViewportSize({width,height:1000});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.ok(await page.locator(".cycle-card-actions").getByRole("button",{name:"Encerrar ciclo",exact:true}).count());
  await page.screenshot({path:"test-results/cycle-actions-"+width+".png",fullPage:true});
  if(width===1280)console.log("VISUAL_CYCLES_ADMIN:"+(await page.screenshot({type:"jpeg",quality:65})).toString("base64"));
 }
 await page.setViewportSize({width:1440,height:1000});
 await nav("Cadastros");
 await page.getByLabel("Código",{exact:true}).first().fill("CI-001");
 await page.getByRole("button",{name:"Abrir / editar produto existente",exact:true}).click();
 await page.getByRole("combobox",{name:"Descrição do produto",exact:true}).click();
 await page.getByRole("listbox",{name:"Valores recentes de Descrição do produto"}).waitFor();
 await page.getByRole("combobox",{name:"Descrição do produto",exact:true}).fill("Resina alterada pela interface");
 await page.getByRole("button",{name:"Salvar nova versão",exact:true}).click();
 await page.getByText("Produto salvo.",{exact:true}).waitFor();
 assert.equal(sql("select version from public.pilot_products where id="+product),"5");
 assert.equal(sql("select product_snapshot->>'name' from public.pilot_cycles where id="+c1),"Resina CI");
 await page.locator(".product-list .history-row").filter({hasText:"CI-001"}).getByRole("button",{name:"Detalhes / versões",exact:true}).click();
 await page.getByRole("dialog",{name:"Versões do produto"}).waitFor();assert.equal(await page.locator(".wide-modal details").count(),5);await page.getByRole("button",{name:"Fechar",exact:true}).click();
 await nav("Usuários");assert.ok(await page.getByText("Operador atualizado",{exact:true}).count());
 await page.screenshot({path:"test-results/users-1440.png",fullPage:true});
 await nav("Autorizações");await page.getByRole("heading",{name:"Histórico de autorizações",exact:true}).waitFor();
 await page.screenshot({path:"test-results/authorizations-1440.png",fullPage:true});
 record("Navegador: duplicidade direciona ao produto, autocomplete, edição gera versão, usuários e histórico");
 await page.getByRole("button",{name:"Sair",exact:true}).click();await page.getByLabel("E-mail",{exact:true}).waitFor();await login("consulta");
 await page.locator(".sidebar nav").getByRole("button",{name:"Ajuda",exact:true}).click();await manual.waitFor();
 await manual.getByText("Atualizado em 02/10/2026 · Seu perfil: Consulta",{exact:true}).waitFor();
 await page.keyboard.press("Escape");await manual.waitFor({state:"hidden"});await nav("Laudos");
 const cancelledRow=page.locator("tbody tr").filter({hasText:number});
 await cancelledRow.click();await page.locator(".cancelled-banner").waitFor();await page.screenshot({path:"test-results/cancelled-certificate-1440.png",fullPage:true});
 assert.equal(await page.locator(".sidebar nav").getByRole("button",{name:"Usuários",exact:true}).count(),0);
 assert.equal(await page.getByRole("button",{name:"Solicitar cancelamento",exact:true}).count(),0);
 for(const width of [1280,1920]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:"test-results/certificate-"+width+".png",fullPage:true});}
 assert.equal(await page.locator("body").getByText(/piloto|protótipo/i).count(),0);
 assert.deepEqual(consoleErrors,[]);
 record("Navegador: Consulta global, laudo CANCELADO consultável, desktop 1280/1440/1920 e console sem erros");
 await browser.close();
 fs.writeFileSync("test-results/results.json",JSON.stringify({status:"passed",evidence},null,2));
 console.log("ALL",evidence.length,"FLOW GROUPS PASSED");
})().catch(async e=>{console.error(e);fs.writeFileSync("test-results/results.json",JSON.stringify({status:"failed",evidence,error:e.message},null,2));if(lastPage){await lastPage.screenshot({path:"test-results/failure.png",fullPage:true});fs.writeFileSync("test-results/failure.html",await lastPage.content());}if(browser)await browser.close();process.exitCode=1});
